/**
 * budgetWorkbook.js — builds the filled roofing budget workbook snapshot.
 *
 * The template is Harmon's ORIGINAL Roofing Budget workbook (all three tabs, original
 * formatting). The writer overwrites every input + computed cell on NEW BUDGET SHEET
 * with plain values from budgetCalc's `cells` map, so the snapshot is a frozen,
 * self-consistent record copy. CITY TAX RATES and ROOFING COMMISSIONS tabs ride along
 * unchanged for reference.
 */
const path = require('path');
const ExcelJS = require('exceljs');

const TEMPLATE_PATH = path.join(__dirname, 'template', 'roofing-budget-template.xlsx');
const SHEET = 'NEW BUDGET SHEET';

async function buildWorkbook(cells, meta = {}) {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(meta.templatePath || TEMPLATE_PATH);
  const ws = wb.getWorksheet(SHEET);

  for (const [ref, value] of Object.entries(cells)) {
    ws.getCell(ref).value = value === undefined ? null : value;
  }

  // Snapshot provenance (out-of-the-way corner)
  ws.getCell('F1').value = 'SNAPSHOT (values only) — generated by Sundial';
  ws.getCell('F2').value = meta.generatedAt || new Date().toISOString();
  if (meta.recordId) ws.getCell('F3').value = `Salesforce: ${meta.recordId}`;

  return wb.xlsx.writeBuffer();
}

/** SUNDIAL/{recordId}/Budget_{ProjectName}_{YYYYMMDD-HHMMSS}.xlsx (same convention as solar) */
function snapshotKey(recordId, projectName, when = new Date()) {
  const safe = String(projectName || 'Project').replace(/[^A-Za-z0-9_-]+/g, '_').slice(0, 60);
  const p = (n) => String(n).padStart(2, '0');
  const stamp = `${when.getUTCFullYear()}${p(when.getUTCMonth() + 1)}${p(when.getUTCDate())}-${p(when.getUTCHours())}${p(when.getUTCMinutes())}${p(when.getUTCSeconds())}`;
  return `SUNDIAL/${recordId}/Budget_${safe}_${stamp}.xlsx`;
}

module.exports = { buildWorkbook, snapshotKey, TEMPLATE_PATH };
