// The field manifest — what each sales role may READ and EDIT, per object.
// D-064, docs/access-model.md §4.2, §4.3. Generated by scripts/generate-field-configs.mjs
// from the workbooks in docs/. Do not hand-edit the JSON; edit the sheet and re-generate.
//
// ---------------------------------------------------------------------------
// THIS MODULE REFUSES TO LOAD RATHER THAN SERVE UNFILTERED (§4.2 item 3)
// ---------------------------------------------------------------------------
// A missing or malformed manifest is not a degraded mode. If the server cannot say
// which fields a role may see, the safe answer is not "all of them" and it is not
// "none of them" — it is that this deploy is broken and must fail at COLD START, where
// it is one loud error in the logs, rather than at request time, where it would be a
// silent leak or a portal full of blank sections.
//
// So the validation below runs at import, and throws. That is deliberate: a Lambda that
// cannot initialise returns 500 for every request and is impossible to miss. A Lambda
// that quietly decided "no manifest, show everything" is a data breach nobody notices.
//
// ---------------------------------------------------------------------------
// TENANT SCOPE IS NOT IN THE MANIFEST, AND THAT IS NOT AN OMISSION
// ---------------------------------------------------------------------------
// §4.1: tenant-wide roles see every field the sheet places in a section, editable per
// the existing describe rules. They are not a column in the workbook and they are not a
// key in `roles` here. Every function below therefore returns "no restriction" for
// tenant scope BEFORE it looks anything up — which is also what keeps Phase 4 from
// touching what Harmon staff see.

import customer from "./customer.json" with { type: "json" };
import solar from "./solar.json" with { type: "json" };
import roofing from "./roofing.json" with { type: "json" };

const MANIFESTS = { customer, solar, roofing };

/** Roles that get a manifest entry. Anything else is tenant-wide or `none`. */
const SALES_ROLES = ["Sales Rep", "Sales Dealer"];

// --- Validation, at import time ---------------------------------------------
function validate(key, m) {
  const where = `field-manifest/${key}.json`;
  if (!m || typeof m !== "object") throw new Error(`${where}: not an object`);
  if (typeof m.version !== "string" || !m.version.startsWith("sha256:")) {
    throw new Error(`${where}: missing or malformed version`);
  }
  if (typeof m.object !== "string" || !m.object) throw new Error(`${where}: missing object`);
  if (!m.roles || typeof m.roles !== "object") throw new Error(`${where}: missing roles`);
  for (const role of SALES_ROLES) {
    const r = m.roles[role];
    if (!r) throw new Error(`${where}: no entry for role "${role}"`);
    if (!Array.isArray(r.read) || !Array.isArray(r.edit)) {
      throw new Error(`${where}: role "${role}" must have read[] and edit[]`);
    }
    // `edit` without `read` would mean a field the user may change but not see. The
    // generator already guarantees this; asserting it here means a hand-edited JSON
    // cannot introduce it either.
    const read = new Set(r.read);
    for (const f of r.edit) {
      if (!read.has(f)) {
        throw new Error(`${where}: role "${role}" has "${f}" as edit but not read`);
      }
    }
  }
  if (!m.listColumns || typeof m.listColumns !== "object") {
    throw new Error(`${where}: missing listColumns`);
  }
}

for (const [key, m] of Object.entries(MANIFESTS)) validate(key, m);

/**
 * One version across all three, so `/auth/me` can hand the client a single string to
 * compare against its own config header. Derived, never stored twice.
 */
export const MANIFEST_VERSION = Object.entries(MANIFESTS)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([k, m]) => `${k}:${m.version.slice(7, 15)}`)
  .join("/");

/** True when this scope is restricted by the manifest at all. */
function isSalesRole(access) {
  return access?.scope === "dealer" || access?.scope === "own";
}

/** The manifest role name for an AccessContext, or null for tenant/none. */
function roleFor(access) {
  if (!isSalesRole(access)) return null;
  const level = access?.level;
  return SALES_ROLES.includes(level) ? level : null;
}

/**
 * `{ read: Set, edit: Set }` for this caller on this object, or `null` meaning
 * "no field restriction applies" (tenant scope).
 *
 * ⚠️ A SALES ROLE WITH NO MANIFEST ENTRY GETS AN EMPTY SET, NOT null. `null` means
 * unrestricted, and the difference between "unrestricted" and "nothing" is the whole
 * module. A level like `Technician` resolves to scope `none` upstream and never reaches
 * here; a sales scope whose level is not a manifest column is a state that should not
 * exist, and the fail-closed answer to it is an empty set.
 */
export function fieldsFor(objectKey, access) {
  if (!isSalesRole(access)) return null; // tenant scope: unrestricted
  const m = MANIFESTS[objectKey];
  if (!m) return { read: new Set(), edit: new Set() };
  const role = roleFor(access);
  if (!role) return { read: new Set(), edit: new Set() };
  const r = m.roles[role];
  return { read: new Set(r.read), edit: new Set(r.edit) };
}

/**
 * The SOQL SELECT list for a `?full=true` read (§4.3).
 *
 * ⚠️ SELECTS ONLY WHAT THE ROLE MAY SEE — it does NOT select everything and strip
 * afterwards. §4.3 is explicit and the reason is worth keeping: data a role may not see
 * should never leave Salesforce. A strip-after-fetch has the hidden values in Lambda
 * memory, in any log line that dumps the record, and in any future code path that
 * forgets to strip. Not fetching them removes the class.
 *
 * Returns null for tenant scope, meaning "the caller's existing all-fields list".
 */
export function selectListFor(objectKey, access, allFieldNames) {
  const f = fieldsFor(objectKey, access);
  if (!f) return null;
  // Id and Client__c are always retained: Id is the record key and Client__c is the
  // tenant control field the WHERE already filters on.
  const keep = new Set(["Id", "Client__c"]);
  for (const name of allFieldNames) if (f.read.has(name)) keep.add(name);
  return [...keep];
}

/**
 * Strip a Salesforce RECORD to the fields this role may read (§4.3).
 * Belt and braces behind selectListFor: the query should already have fetched only
 * these, so this should be a no-op — and if it ever is not, the response is still right.
 */
export function projectRecord(objectKey, access, record) {
  const f = fieldsFor(objectKey, access);
  if (!f || !record) return record;
  const out = {};
  for (const [k, v] of Object.entries(record)) {
    if (k === "Id" || k === "Client__c" || f.read.has(k)) out[k] = v;
  }
  return out;
}

/**
 * Strip a CACHE ROW to the columns this role may read (§4.3), for list and search.
 * Column-based rather than field-based because that is the shape the cache serves.
 */
export function projectRow(objectKey, access, row) {
  const cols = listColumnsFor(objectKey, access);
  if (!cols || !row) return row;
  const out = {};
  for (const [k, v] of Object.entries(row)) if (cols.has(k)) out[k] = v;
  return out;
}

/** The cache columns this role's list rows may carry, or null for tenant scope. */
export function listColumnsFor(objectKey, access) {
  if (!isSalesRole(access)) return null;
  const m = MANIFESTS[objectKey];
  if (!m) return new Set();
  const role = roleFor(access);
  if (!role) return new Set();
  return new Set(m.listColumns[role] ?? []);
}

/**
 * The `access.editable` block returned beside a `?full=true` record (§4.3), so the
 * client can render a field read-only without deciding anything itself.
 */
export function editableFor(objectKey, access) {
  const f = fieldsFor(objectKey, access);
  return f ? [...f.edit].sort() : null;
}

/** Is this field editable by this caller? The write path's question (§3.4 step 3). */
export function canEditField(objectKey, access, fieldName) {
  const f = fieldsFor(objectKey, access);
  if (!f) return null; // tenant scope: the caller applies its own describe rules
  return f.edit.has(fieldName);
}

export { MANIFESTS };
