-- sundial_membership_cache — Supabase cache table for Sundial_Membership__c (Service Club Membership, D-073).
--
-- Same pattern as the D-072 service caches: the display subset the portal's lists render,
-- plus the standard control columns. Column NAMES match sfFieldToColumn() (strip __c,
-- lowercase; reference fields get _sf_id), so creating this table makes membership records
-- populate via read-through and the scheduled sundial-cache-sync job. GENERATED by
-- scripts/gen-service-club.py - edit the spec, not this.
--
-- TENANT ISOLATION: client_sf_id is the isolation key (D-035), NOT NULL.

create table if not exists sundial_membership_cache (
  -- Control / identity
  sf_id                        text primary key,          -- Salesforce record Id
  client_sf_id                 text not null,             -- Client__c (tenant isolation key)
  tenant_id                    text,                      -- Client__r.Name slug (label only)

  -- Display subset
  name                         text,        -- Name (auto-number)
  sundial_customer_sf_id       text,        -- Sundial_Customer__c (Required.)
  service_plan_sf_id           text,        -- Service_Plan__c (Required.)
  customer_name_at_creation    text,        -- Customer_Name_at_Creation__c (Snapshot at record creation (standard snapshot pattern).)
  address_at_creation          text,        -- Address_at_Creation__c (Snapshot at record creation.)
  primary_phone_at_creation    text,        -- Primary_Phone_at_Creation__c (Snapshot at record creation.)
  primary_email_at_creation    text,        -- Primary_Email_at_Creation__c (Snapshot at record creation.)
  status                       text,        -- Status__c (Pending (checkout started) -> Active -> Past Due (renewal fa...)
  billing_interval             text,        -- Billing_Interval__c
  price                        numeric,     -- Price__c (What the member pays per interval, as sold.)
  source                       text,        -- Source__c (Online = the public join page. Office = a join link sent fro...)
  stripe_subscription_id       text,        -- Stripe_Subscription_Id__c (External ID - the webhook's idempotency key.)
  stripe_checkout_session_id   text,        -- Stripe_Checkout_Session_Id__c (The session the join minted; the success page looks the memb...)
  stripe_customer_id           text,        -- Stripe_Customer_Id__c (Mirror of the customer hub's, at join time.)
  started_at                   timestamptz, -- Started_At__c (When the subscription became Active.)
  current_period_end           timestamptz, -- Current_Period_End__c (From Stripe; the next renewal.)
  cancel_at_period_end         boolean,     -- Cancel_At_Period_End__c (Cancelled by the member or the office, still Active until th...)
  cancelled_at                 timestamptz, -- Cancelled_At__c (When the cancellation was requested.)
  ended_at                     timestamptz, -- Ended_At__c (When the subscription actually ended (Stripe's customer.subs...)
  cancel_reason                text,        -- Cancel_Reason__c
  last_payment_at              timestamptz, -- Last_Payment_At__c
  last_payment_amount          numeric,     -- Last_Payment_Amount__c
  lifetime_revenue             numeric,     -- Lifetime_Revenue__c (Sum of Stripe invoice.paid amounts on this subscription.)
  payment_failures             numeric,     -- Payment_Failures__c (Count of invoice.payment_failed events.)
  solarfacts_status            text,        -- SolarFacts_Status__c (The monitoring hand-off (D-073.6): Not Sent -> Sent on activ...)
  solarfacts_last_sent_at      timestamptz, -- SolarFacts_Last_Sent_At__c
  solarfacts_last_error        text,        -- SolarFacts_Last_Error__c
  solarfacts_account_id        text,        -- SolarFacts_Account_Id__c (SolarFax's account_id from POST /users (their API), for supp...)
  solarfacts_user_id           text,        -- SolarFacts_User_Id__c (SolarFax's user_id from POST /users.)
  notes                        text,        -- Notes__c

  created_date                 timestamptz, -- CreatedDate (list ordering)
  last_synced_at               timestamptz not null default now(),
  cache_version                integer not null default 1,
  is_stale                     boolean not null default false
);

create index if not exists idx_sundial_membership_cache_tenant
  on sundial_membership_cache (client_sf_id);
create index if not exists idx_sundial_membership_cache_customer
  on sundial_membership_cache (client_sf_id, sundial_customer_sf_id);
create index if not exists idx_sundial_membership_cache_status
  on sundial_membership_cache (client_sf_id, status);
create index if not exists idx_sundial_membership_cache_plan
  on sundial_membership_cache (client_sf_id, service_plan_sf_id, status);
create index if not exists idx_sundial_membership_cache_subscription
  on sundial_membership_cache (stripe_subscription_id) where stripe_subscription_id is not null;
create index if not exists idx_sundial_membership_cache_recent
  on sundial_membership_cache (client_sf_id, created_date desc nulls last, sf_id);
create index if not exists idx_sundial_membership_cache_stale
  on sundial_membership_cache (client_sf_id, is_stale) where is_stale = true;
