-- sundial_service_plan_cache — Supabase cache table for Sundial_Service_Plan__c (Service Plan, D-073).
--
-- Same pattern as the D-072 service caches: the display subset the portal's lists render,
-- plus the standard control columns. Column NAMES match sfFieldToColumn() (strip __c,
-- lowercase; reference fields get _sf_id), so creating this table makes serviceplan records
-- populate via read-through and the scheduled sundial-cache-sync job. GENERATED by
-- scripts/gen-service-club.py - edit the spec, not this.
--
-- TENANT ISOLATION: client_sf_id is the isolation key (D-035), NOT NULL.

create table if not exists sundial_service_plan_cache (
  -- Control / identity
  sf_id                     text primary key,          -- Salesforce record Id
  client_sf_id              text not null,             -- Client__c (tenant isolation key)
  tenant_id                 text,                      -- Client__r.Name slug (label only)

  -- Display subset
  name                      text,        -- Name (text)
  plan_code                 text,        -- Plan_Code__c (Stable key per tenant (monitor / maintain / clean / protect ...)
  kind                      text,        -- Kind__c (Subscription = a recurring Stripe subscription (monthly / ye...)
  availability              text,        -- Availability__c (Available = on the public page and purchasable. Coming Soon ...)
  sort_order                numeric,     -- Sort_Order__c (Public page order.)
  highlight                 text,        -- Highlight__c (Badge on the public card, e.g. MOST POPULAR. Blank = none.)
  tagline                   text,        -- Tagline__c (One line under the plan name.)
  monthly_price             numeric,     -- Monthly_Price__c (Subscription plans: per month.)
  yearly_price              numeric,     -- Yearly_Price__c (Subscription plans: per year (blank = no yearly option).)
  price                     numeric,     -- Price__c (One-time plans: the amount charged at purchase.)
  price_book_item_code      text,        -- Price_Book_Item_Code__c (One-time plans: the price-book Item_Code__c that becomes the...)
  stripe_product_id         text,        -- Stripe_Product_Id__c (Written by the seed script.)
  stripe_monthly_price_id   text,        -- Stripe_Monthly_Price_Id__c (Written by the seed script; replaced (old archived) when Mon...)
  stripe_yearly_price_id    text,        -- Stripe_Yearly_Price_Id__c (Written by the seed script.)
  discount_scope            text,        -- Discount_Scope__c (What the member discount applies to on an estimate - the est...)
  discount_type             text,        -- Discount_Type__c
  discount_value            numeric,     -- Discount_Value__c (10 = 10% (Percent) or $10 (Amount). Blank / 0 = the plan car...)
  discount_description      text,        -- Discount_Description__c (How the office and the customer read it, e.g. '10% off repai...)
  includes_tune_up          boolean,     -- Includes_Tune_Up__c (The office owes the member one tune-up a year.)
  includes_cleaning         boolean,     -- Includes_Cleaning__c (The office owes the member one panel cleaning a year.)
  notes                     text,        -- Notes__c

  created_date              timestamptz, -- CreatedDate (list ordering)
  last_synced_at            timestamptz not null default now(),
  cache_version             integer not null default 1,
  is_stale                  boolean not null default false
);

create index if not exists idx_sundial_service_plan_cache_tenant
  on sundial_service_plan_cache (client_sf_id);
create index if not exists idx_sundial_service_plan_cache_code
  on sundial_service_plan_cache (client_sf_id, plan_code);
create index if not exists idx_sundial_service_plan_cache_availability
  on sundial_service_plan_cache (client_sf_id, availability, sort_order);
create index if not exists idx_sundial_service_plan_cache_recent
  on sundial_service_plan_cache (client_sf_id, created_date desc nulls last, sf_id);
create index if not exists idx_sundial_service_plan_cache_stale
  on sundial_service_plan_cache (client_sf_id, is_stale) where is_stale = true;
