/**
 * budgetWorkbook.js — builds the filled budget workbook snapshot.
 *
 * Loads the bundled template (the REVISED workbook, Harmon's current budget
 * sheet — swap the file any time, the writer only addresses cells) and
 * writes every input + computed value from budgetCalc's `cells` map as plain values.
 * Formula cells are overwritten with their computed results so the snapshot is a
 * frozen, self-consistent record copy that can never drift from what Salesforce shows.
 */
const path = require('path');
const ExcelJS = require('exceljs');

const TEMPLATE_PATH = path.join(__dirname, 'template', 'budget-template-v2.xlsx');

// Runtime template source. `template.generated.js` is a BUILD ARTIFACT produced by
// prebuild.mjs at deploy time — it base64-encodes template/budget-template-v2.xlsx so
// the single esbuild bundle carries the exact REVISED-workbook bytes with no file
// on disk (the bundled Lambda has no template/ folder). It is gitignored and absent
// during `npm test`, so tests read the source .xlsx directly — meaning the tested
// template and the shipped template are the SAME bytes by construction and cannot
// drift. Decoding here needs no /tmp path: ExcelJS loads straight from the Buffer.
let EMBEDDED_TEMPLATE = null;
try {
  EMBEDDED_TEMPLATE = Buffer.from(require('./template.generated.js').TEMPLATE_BASE64, 'base64');
} catch {
  /* not embedded (tests / local) -> fall back to reading the source .xlsx */
}

async function buildWorkbook(cells, meta = {}) {
  const wb = new ExcelJS.Workbook();
  if (meta.templatePath) {
    await wb.xlsx.readFile(meta.templatePath);
  } else if (EMBEDDED_TEMPLATE) {
    await wb.xlsx.load(EMBEDDED_TEMPLATE);
  } else {
    await wb.xlsx.readFile(TEMPLATE_PATH);
  }
  const ws = wb.getWorksheet('Sheet1');

  for (const [ref, value] of Object.entries(cells)) {
    ws.getCell(ref).value = value === undefined ? null : value;
  }

  // Stamp snapshot provenance in an out-of-the-way spot
  ws.getCell('L2').value = 'SNAPSHOT (values only) — generated by Sundial';
  ws.getCell('L3').value = meta.generatedAt || new Date().toISOString();
  if (meta.recordId) ws.getCell('L4').value = `Salesforce: ${meta.recordId}`;

  return wb.xlsx.writeBuffer();
}

/** SUNDIAL/{recordId}/Budget_{ProjectName}_{YYYYMMDD-HHMMSS}.xlsx */
function snapshotKey(recordId, projectName, when = new Date()) {
  const safe = String(projectName || 'Project').replace(/[^A-Za-z0-9_-]+/g, '_').slice(0, 60);
  const p = (n) => String(n).padStart(2, '0');
  const stamp = `${when.getUTCFullYear()}${p(when.getUTCMonth() + 1)}${p(when.getUTCDate())}-${p(when.getUTCHours())}${p(when.getUTCMinutes())}${p(when.getUTCSeconds())}`;
  return `SUNDIAL/${recordId}/Budget_${safe}_${stamp}.xlsx`;
}

module.exports = { buildWorkbook, snapshotKey, TEMPLATE_PATH };
