// prebuild.mjs — deploy-time build step for sundial-budget (run by deploy.ps1
// before esbuild bundles). Reads the source-of-record template
// template/budget-template.xlsx and emits template.generated.js exporting its
// base64 so the single bundle carries the exact bytes. NOT hand-maintained and
// NOT committed (gitignored); regenerated from the .xlsx on every deploy, so the
// embedded template can never drift from the source file the tests run against.
//
// To swap the template: replace template/budget-template.xlsx in the repo, run
// `npm test`, rebuild, redeploy. No base64 is ever edited by hand.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const templatePath = join(here, "template", "budget-template.xlsx");
const outPath = join(here, "template.generated.js");

const b64 = readFileSync(templatePath).toString("base64");

// CommonJS module so budgetWorkbook.js (CJS) can require() it; esbuild inlines it.
const banner =
  "// AUTO-GENERATED by prebuild.mjs from template/budget-template.xlsx — DO NOT EDIT, DO NOT COMMIT.\n";
writeFileSync(outPath, `${banner}module.exports = { TEMPLATE_BASE64: ${JSON.stringify(b64)} };\n`);

console.log(
  `prebuild: embedded template (${b64.length} base64 chars) -> ${outPath}`
);
